name: Docker Image CI

on:
  push:
    # branches: [ staging ]
  pull_request:
    # branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build image
        run: docker build . --file Dockerfile --tag django-dev

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: hercip
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      -
        name: Publish
        run: |
          docker tag django-dev hercip/django-dev
          docker push hercip/django-dev